# Generated by Django 4.2 on 2024-06-25 19:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_contactoform_mensaje_cifrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactoForm',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje_cifrado',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
